[package]
name = "merkle_proof_verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "1.0.2", features = ["abigen", "rustls"] }
tokio = { version = "1.24.1", features = ["full"] }
